from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Any

# Contract for raw structural chunks extracted from the document
class ExtractedElement(BaseModel):
    content: str = Field(description="The raw extracted text, markdown layout table, or image metadata string.")
    element_type: str = Field(description="Classification token like Paragraph, Header, TableItem, or PictureItem.")
    source_page: Optional[int] = Field(default=1, description="The specific page number from the parsed file.")

# Contract for AI-enriched metadata generated by the local text LLM
class ChunkMetadata(BaseModel):
    summary: str = Field(description="A concise one-sentence context summary of this specific text chunk.")
    keywords: List[str] = Field(description="Generated high-impact keywords for rapid filtering.")
    category: str = Field(description="Topic classification tag (e.g., Financials, Technical, Compliance).")
    parent_context_id: Optional[str] = Field(default=None, description="UUID pointer to a parent block for broad lookups.")

# The unified payload contract prepared for Pinecone vector storage
class FinalVectorPayload(BaseModel):
    id: str = Field(description="A unique generated deterministic UUID hash.")
    vector: Optional[List[float]] = Field(default=None, description="The 1024-dimensional embedding array.")
    text_content: str = Field(description="The raw semantic text indexed by this vector.")
    metadata: Dict[str, Any] = Field(description="Flat JSON object containing combined structural and AI metadata fields.")